source_files =  (
    "mpi.c",
)

def build(ctx):
    ctx.stlib(source=source_files,
              includes=['#/valgrind/include', '#/include'],
              target="aislinn_mpi",
              name="aislinn_mpi")


