source_files =  (
    "mpi.c",
)

def build(ctx):
    ctx(rule="${PYTHON} ${SRC} ${TGT}", source='buildhelper.py mpi.h', target='mpi.c')
    ctx.stlib(source=source_files,
              includes=['#/valgrind/include', '#/include'],
              target="aislinn_mpi",
              name="aislinn_mpi")


