
def build(ctx):
    ctx(features="py",
        source=["aislinn.py"],
        install_path="${PREFIX}/lib/aislinn/aislinn")

    for directory in ["vgtool", "base", "mpi"]:
        files = ctx.path.ant_glob(directory + "/*.py")
        ctx(features="py",
            source=files,
            install_path="${PREFIX}/lib/aislinn/aislinn/" + directory)

    # Templates
    files = ctx.path.ant_glob("template/*.html")
    ctx.install_files("${PREFIX}/lib/aislinn/aislinn/template", files)
